### ISSUE TITLE
Error "Cannot find module axios.cjs"

### ISSUE THREAD

**Issue by technocolour** [paritytech/zombienet#569] opened 2022-11-06 18:10 UTC
I downloaded the [latest release](https://github.com/paritytech/zombienet/releases/tag/v1.3.12) and tried to run it in the [`trappist`](https://github.com/paritytech/trappist) directory, as said in the [XCM-playground tutorial](https://docs.google.com/presentation/d/1V_Lk53TX-KGdzX3HSrPMQUEt_ARa7i6F64WH9zRofEo/edit#slide=id.g13005c28bfd_1_5): 
Running `./zombienet-macos -p native spawn` I get 

```
pkg/prelude/bootstrap.js:1876
      throw error;
      ^

Error: Cannot find module '/snapshot/zombienet/node_modules/axios/dist/node/axios.cjs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at createEsmNotFoundErr (node:internal/modules/cjs/loader:960:15)
    at finalizeEsmResolution (node:internal/modules/cjs/loader:953:15)
    at resolveExports (node:internal/modules/cjs/loader:482:14)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at Module.require (pkg/prelude/bootstrap.js:1855:31)
    at require (node:internal/modules/cjs/helpers:102:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/snapshot/zombienet/node_modules/axios/package.json',
  pkg: true
}
```

Node.js v18.11.0

Also ran `npm install` and `npm install axios` to no avail

**Comment by technocolour** [comment] 2022-11-06 18:49
Note: It works with v.1.2.61

**Comment by pepoviola** [comment] 2022-11-07 19:22
Hi @technocolour, I can't reproduce with the latest version. Can you run

```
 ./zombienet-macos version
```
and send me the version?

Thanks!!

**Comment by pepoviola** [comment] 2022-12-06 17:23
Hi @technocolour, closing here. Please re-open if you still have this issue with the latest release.
Thanks!

**Closed by pepoviola** 2022-12-06 17:23 UTC
Labels: question
