### ISSUE TITLE
Zombienet reports failure even though conditions are met

### ISSUE THREAD

**Issue by skunert** [paritytech/zombienet#1652] opened 2024-01-08 14:55 UTC
Test in question runs on CI: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4864909
Test file: https://github.com/paritytech/polkadot-sdk/blob/master/cumulus/zombienet/tests/0002-pov_recovery.zndsl

Zombienet reports:
```
 1/8/2024, 2:07:54 PM         │ ❌ three: count of log lines containing "Importing block retrieved using pov_recovery" is greater… │
```
It is omitted here, but from the test file we see that we should check that the log line should appear more than 19 times.

However, if I click the grafana link and search for "Importing block retrieved using pov_recovery" I find 22 hits in the time range.
<img width="1499" alt="image" src="https://github.com/paritytech/zombienet/assets/5718005/65cdae0d-ecfb-4987-bf7d-d53dec0247b8">

So I would have expected this zombienet test to succeed.

---
Additional problem: When I download the logs from the artifacts in gitlab, the logs for node "three" are incomplete. They only cover the last minute or so of the run, even though grafana has more logs available. Not sure how that happens.

Faulty log here: https://gitlab.parity.io/parity/mirrors/polkadot-sdk/-/jobs/4864909/artifacts/external_file/zombienet-logs/three.log

**Comment by pepoviola** [comment] 2024-01-08 15:08
Hi @skunert thanks for reporting, the root cause of this issue is that we are using `kubectl` to access the logs and could be that the logs from the host vm were rotated so the the logs we get from `k8s` are truncated. We have this https://github.com/paritytech/zombienet/issues/1565 tracking the fix, I will try to fix today and draft a new release asap.

Thx!!

**Comment by pepoviola** [comment] 2024-04-09 20:46
Hi @skunert, this should be already fixed. Closing here.
Thx!

**Closed by pepoviola** 2024-04-09 20:46 UTC
Labels: bug
