### ISSUE TITLE
Failing test with: `input.forEach` is not a function

### ISSUE THREAD

**Issue by wirednkod** [paritytech/zombienet#778] opened 2023-03-09 07:45 UTC
```
Error: Timeout(300) for transfer container for pod : honest-validator-4
    at KubeClient.<anonymous> (/home/nonroot/zombie-net/dist/providers/k8s/kubeClient.js:225:19)
    at Generator.next (<anonymous>)
    at fulfilled (/home/nonroot/zombie-net/dist/providers/k8s/kubeClient.js:28:58)
Error launching the network!
	 TypeError: input.forEach is not a function
 exit code 100
 ```
 
 Examples:
 https://gitlab.parity.io/parity/mirrors/polkadot/builds/2500393
 https://gitlab.parity.io/parity/mirrors/polkadot/builds/2500356

**Comment by pepoviola** [comment] 2023-03-09 10:48
ping @emamihe can you review the logs of the cluster. We need to know if the cause is some bottleneck in the infra.
Thanks!

**Comment by pepoviola** [comment] 2023-04-18 12:01
Closing here. Thanks!

**Closed by pepoviola** 2023-04-18 12:01 UTC
Labels: bug
