### ISSUE TITLE
Error: Race when use multiple parachains in native (default concurrency)

### ISSUE THREAD

**Issue by ysfkel** [paritytech/zombienet#1237] opened 2023-08-11 15:09 UTC
### Issue Description

I am getting the following error when i try to initialize a network with the current release of substrate-parachain-template polkadot-v1.0.0 
This error only occurs with the latest release polkadot-v1.0.0  and not previous versions eg  polkadot-v0.9.43
I used the following command to initialize the network 

`zombienet-macos -p native spawn zombienet-config.toml`

Error 
```
Error: Command failed with exit code 1: bash -c ./binaries/parachain-template-node-v1.0.0 export-genesis-state -- 
  chain /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-475aae300fa5e3392febe432f0ca4962_-65226-56tgjqhF6n5o/1001-rococo-local.json > /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-475aae300fa5e3392febe432f0ca4962_-65226-56tgjqhF6n5o/cfg/genesis-state-1001 && ./binaries/parachain-template-node-v1.0.0 export-genesis-wasm 
--chain /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-475aae300fa5e3392febe432f0ca4962_-65226-56tgjqhF6n5o/1001-rococo-local.json > /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-475aae300fa5e3392febe432f0ca4962_-65226-56tgjqhF6n5o/cfg/genesis-wasm-1001
  Error: Service(Client(Backend("IO error: While lock file: /Users/me/Library/Application Support/parachain-template-node-v1.0.0/chains/local_testnet/db/full/LOCK: Resource temporarily unavailable")))

```

### Steps to reproduce the issue

 
config 

```
[settings]
timeout = 1000

[relaychain]
default_command = "binaries/polkadot-v1.0.0"
default_args = [ "-lparachain=debug" ] 
chain = "rococo-local"

    [[relaychain.nodes]]
    name = "alice"
    validator = true
    ws_port = 9900

    [[relaychain.nodes]]
    name = "bob"
    validator = true

    [[relaychain.nodes]]
    name = "charlie"
    validator = true

    [[relaychain.nodes]]
    name = "dave"
    validator = true

[[parachains]]
id = 1000
cumulus_based = true
add_to_genesis = true
chain = "template-rococo"

    [parachains.collator]
    command = "./binaries/parachain-template-node-v1.0.0"
    name = "parachain-A-1000-collator01"
    ws_port = 9910
    args = ["--log=xcm=trace,pallet-assets=trace"]

[[parachains]]
id = 1001
add_to_genesis = true
cumulus_based = true

    [parachains.collator]
    command = "./binaries/parachain-template-node-v1.0.0"
    name = "parachain-B-1001-collator01"
    ws_port = 9920
    args = ["--log=xcm=trace,pallet-assets=trace"]


[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"

[[hrmp_channels]]
sender = 1000
recipient = 1001 
max_capacity = 8
max_message_size = 512

[[hrmp_channels]]
sender = 1001
recipient = 1000
max_capacity = 8
max_message_size = 512
```

### Zombienet version

1.3.64

### Provider

Native

**Comment by Lord-Nymphis** [comment] 2023-08-11 20:22
Hi @pepoviola ; can you please take a look when is possible for you? :)

**Comment by Lord-Nymphis** [comment] 2023-08-11 20:34
Or @wirednkod , perhaps: we accept help from every Farthing of the Shire ;)

**Comment by pepoviola** [comment] 2023-08-11 23:13
Hi @ysfkel / @Lord-Nymphis, thanks for reporting and the feedback. I can reproduce the issue and looks like a `race` condition in the locking of the db. I will check why is happens with `v1` and not with `0.9.43`. One workaround to spawn/test with zombienet is to set the `concurrency` (with the flag `-c`) to 1 and I testes that works as expected.

```
zombienet-macos -p native -c 1 spawn zombienet-config.toml
```

**Comment by Lord-Nymphis** [comment] 2023-08-15 07:26
Thank you, seems that your suggestion is helpful to fix the issue!

**Comment by ysfkel** [comment] 2023-08-15 20:37
Hey @pepoviola it works with -c 1 . Could you have a look at this as well https://github.com/paritytech/zombienet/issues/1238 thanks

**Comment by pepoviola** [comment] 2024-01-08 12:30
Hi @ysfkel, this is fixed in the latest version (by this [pr](https://github.com/paritytech/zombienet/pull/1638)).
Closing here, please re-open if needed.
Thx!

**Closed by pepoviola** 2024-01-08 12:30 UTC
Labels: support
