### ISSUE TITLE
Error pulling image for pod

### ISSUE THREAD

**Issue by sacha-l** [paritytech/zombienet#584] opened 2022-11-13 16:13 UTC
I'm trying to launch a zombienet using Docker on macOS but get the following error:

```bash
Error: Error pulling image for pod : temp
    at KubeClient.<anonymous> (/snapshot/javascript/packages/orchestrator/dist/providers/k8s/kubeClient.js)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/javascript/packages/orchestrator/dist/providers/k8s/kubeClient.js)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here's the toml file:

```toml
[relaychain]
default_image = "docker.io/paritypr/polkadot-debug:master"
default_command = "polkadot"
default_args = [ "-lparachain=debug" ]

chain = "rococo-local"

  [[relaychain.nodes]]
  name = "alice"
  validator = true

  [[relaychain.nodes]]
  name = "bob"
  validator = true

[[parachains]]
id = 1000

  [parachains.collator]
  name = "collator01"
  image = "/bin/parachain-v0.9.30-1000"
  command = "adder-collator"
```

It's not clear what's causing this error and how to fix it. Any pointers appreciated.

**Comment by pepoviola** [comment] 2022-11-13 19:13
Hi @sacha-l, thanks for report. In this case the issue is with the collator config

```
image = "/bin/parachain-v0.9.30-1000"
```
This should be a valid image (e.g docker.io/repo/image:version)

But we should work to improve the error reporting.
Thanks!!

**Comment by pepoviola** [comment] 2022-11-14 10:10
Closing here, follow up in this issue https://github.com/paritytech/zombienet/issues/585 .
Thanks!!

**Closed by pepoviola** 2022-11-14 10:10 UTC
