### ISSUE TITLE
Parachains block production getting stuck

### ISSUE THREAD

**Issue by NachoPal** [paritytech/zombienet#1078] opened 2023-05-22 10:32 UTC
### Issue Description

I am using `@zombienet/cli` `1.3.52` package version , and sometimes (maybe 50% of the time), the parachains get stuck for some minutes around block 2 or 3, but they eventually resume building blocks. I do not know if someone else have experienced it or it is a local issue I have.

### Steps to reproduce the issue

Steps to reproduce the issue
1. `zombienet -p native spawn`

with `config.toml`

```
[relaychain]
default_command = "./bin/polkadot"
default_args = [ "-lparachain=trace", "-lxcm=trace" ]
chain = "polkadot-local"

    [[relaychain.nodes]]
    name = "alice"
    ws_port = 9700
    validator = true
    args = ["--state-cache-size=0"]

    [[relaychain.nodes]]
    name = "bob"
    ws_port = 9701
    validator = true

    [[relaychain.nodes]]
    name = "charlie"
    ws_port = 9702
    validator = true

    [[relaychain.nodes]]
    name = "dave"
    ws_port = 9703
    validator = true

[[parachains]]
id = 1001
chain = "collectives-polkadot-local"
cumulus_based = true

    [[parachains.collators]]
    name = "collator1"
    ws_port = 9710
    command = "./bin/polkadot-parachain"
    args = [ "-lxcm=trace", "--state-cache-size=0" ]

    [[parachains.collators]]
    name = "collator2"
    ws_port = 9711
    command = "./bin/polkadot-parachain"
    args = ["-lxcm=trace"]
```

### Describe the results you received

The parachains get stuck for some minutes around block 2 or 3

### Describe the results you expected

They should get stuck for some minutes. They should produce blocks every 12 seconds

### Zombienet version

1.3.52

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 0.9.42
polkadot-parachain 0.9.42
```

### Upstream Latest Release

Yes

### Additional information

Issue happens only occasionally

**Comment by wirednkod** [comment] 2023-05-23 16:39
When running with the same `configuration` but just with 1 collator of the parachain, then there are no  delays in the block production and the parachain seems to finalize blocks normally.

**Comment by wirednkod** [comment] 2023-05-26 09:48
@NachoPal there seemed to be an eviction between the 2 collators starting pretty early, before they received a relay chain block and start producing blocks,  when the nodes were spawning. There is a fix to the issue through [this PR](https://github.com/paritytech/substrate/pull/14216).

I will close this for now - and please reopen if the issue is reproduced;

**Closed by wirednkod** 2023-05-26 09:48 UTC
