### ISSUE TITLE
Make start-para-mac -  Error: Command failed with exit code 1: bash -c

### ISSUE THREAD

**Issue by ysfkel** [paritytech/zombienet#1238] opened 2023-08-12 09:48 UTC
### Issue Description

I get the following error when I run the poc with  `make start-para-mac`.
```
Error:  	 Error: Command failed with exit code 1: bash -c ./target/release/rialto-bridge-node build-spec --chain /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json --disable-default-bootnode  --raw > /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-raw.json
Error: Input("Unsupported chain specification: /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json")

undefined
Node'  s logs:              /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-Qs…

 Error:  	 Error: Command failed with exit code 1: bash -c kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]                                                                      
```

### Zombienet version

1.3.64

### Provider

Native

**Comment by Lord-Nymphis** [comment] 2023-08-16 09:42
@pepoviola

**Comment by pepoviola** [comment] 2023-08-16 10:46
Hi @ysfkel / @Lord-Nymphis, thanks for reporting. Doesn't look like a zombienet issue but if you pointing me to the repo where I can reproduce this I can take a look.

Thanks!

**Comment by ysfkel** [comment] 2023-08-16 10:58
Hey @pepoviola sure it's occurring in this repo https://github.com/paritytech/solo-para-bridge-poc
by running the command > `make start-para-mac `

**Comment by Lord-Nymphis** [comment] 2023-08-17 09:46
Hi @pepoviola . I had a conversation with @pawanbisht62 , that is one of the main devs working on the solo-para-bridge-poc. I asked him if the solo-para-bridge-poc is currently working with zombienet and he explained me that is not currently working with it. The solo-para-bridge-poc team has updated the repo and resolved the compilation issues, but it is still not working (apparently the bridges team is working with zombienet team to fix it), but he said that, for the moment, it must be spinned manually.

Can you please take a look @pepoviola ?

**Comment by Lord-Nymphis** [comment] 2023-09-09 11:17
Hi @pepoviola for the moment we have been spinning manually everything because of this.

@ysfkel

**Comment by ysfkel** [comment] 2023-09-11 08:05
> Error:  	 Error: Command failed with exit code 1: bash -c ./target/release/rialto-bridge-node build-spec --chain /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json --disable-default-bootnode  --raw > /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-raw.json
> Error: Input("Unsupported chain specification: /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json")
> 
> undefined
> Node'  s logs:              /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-Qs…
> 
>  Error:  	 Error: Command failed with exit code 1: bash -c kill -9
> kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]

This is the error 
```
Error:  	 Error: Command failed with exit code 1: bash -c ./target/release/rialto-bridge-node build-spec --chain /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json --disable-default-bootnode  --raw > /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-raw.json
Error: Input("Unsupported chain specification: /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-QsYDje1BT6hq/local-plain.json")

undefined
Node'  s logs:              /var/folders/hm/qpzbwhn15518j2xscdc4h_y00000gn/T/zombie-74b43d6c6c3202766910d4ec2ff6610d_-2401-Qs…

 Error:  	 Error: Command failed with exit code 1: bash -c kill -9
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]  
```

**Comment by pepoviola** [comment] 2023-09-11 12:40
Hi @ysfkel, thanks for the update. we should check what are causing this error `Unsupported chain specification` in the node's logic, since that command looks ok. I will try to reproduce today.
Thx!

**Comment by pepoviola** [comment] 2024-03-08 17:48
Closing here @ysfkel, please re-open if still needed.
Thx!

**Closed by pepoviola** 2024-03-08 17:48 UTC
Labels: question, support
