### ISSUE TITLE
`command` vs `default_command`

### ISSUE THREAD

**Issue by mrcnski** [paritytech/zombienet#1681] opened 2024-01-15 11:49 UTC
We were debugging a zombienet test that uses `command` fields:

https://github.com/paritytech/polkadot-sdk/blob/70852e9400ea7931d01be4ddd670d8aa94a49bbc/polkadot/zombienet_tests/smoke/0001-parachains-smoke-test.toml#L24

@s0me0ne-unkn0wn commented:

> On my side, when I specified full binary path under `command`, it was just ignored and defaulted to `polkadot` without path specification. The I looked into my other Zombienet configs and found out it's `default_command` everywhere else. I suppose `command` is silently ignored and polkadot is just the default value

## TODO:

1. [ ] Which field is correct? We should update all polkadot zombienet tests to use the correct one.
2. [ ] Is zombienet ignoring invalid fields? It should at least throw a warning.

**Comment by pepoviola** [comment] 2024-01-15 12:11
Thanks for reporting, I will fix asap.
Thx!

**Comment by mrcnski** [comment] 2024-01-15 12:51
Thanks @pepoviola! But I would say this is not urgent, so you can enjoy your vacation!

**Comment by pepoviola** [comment] 2024-01-16 11:53
Hi @mrcnski, I checked this one and the issue is in the config. The `command` field is at node level, and override (if present) the default command for all the nodes in the `relay chain`.

```toml
[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lruntime=debug,parachain=trace" ]
```

Should be

```toml
[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]
  command = "polkadot"

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lruntime=debug,parachain=trace" ]
```

Alice will be using `polkadot` as command and bob the one defined in `default_command`.

Can you check with this config please?
Thx!

**Comment by mrcnski** [comment] 2024-01-19 13:06
@pepoviola You meant this, correct? (`[relaychain]` should have `default_command`).

```toml
[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
default_command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  args = [ "--alice", "-lruntime=debug,parachain=trace" ]
  command = "polkadot"

  [[relaychain.nodes]]
  name = "bob"
  args = [ "--bob", "-lruntime=debug,parachain=trace" ]
```

If that's the case then we should fix the zombienet tests in `polkadot-sdk`, and maybe make zombienet throw a warning for incorrect configurations.

**Comment by pepoviola** [comment] 2024-01-20 13:09
Hi @mrcnski, yes. Should be `default_command` in the relaychain (I updated in my comment). 

> maybe make zombienet throw a warning for incorrect configurations.

Also yes, in general we are just silently ignoring any config key typo/error and we had the idea to add a json schema validation at some point (https://github.com/paritytech/zombienet/issues/662). But, with the progress of the new version this task priority was move to a nice to have. Maybe we can revisit later this quater.

Thanks!!

**Comment by pepoviola** [comment] 2024-05-24 13:27
Hi @mrcnski, closing here. Please re-open if needed.
Thanks for your feedback!

**Closed by pepoviola** 2024-05-24 13:27 UTC
Labels: enhancement, good first issue
