### ISSUE TITLE
Error fetching metrics from: http://127.0.0.1:56776/metrics

### ISSUE THREAD

**Issue by brunopgalvao** [paritytech/zombienet#1786] opened 2024-05-01 08:12 UTC
### Issue Description

I am getting the following error repeatedly then my network does not boot up.
```
Error fetching metrics from: http://127.0.0.1:56776/metrics
```

### Steps to reproduce the issue

Steps to reproduce the issue
1. Use release [v1.3.100](https://github.com/paritytech/zombienet/releases/tag/v1.3.100)
2. `./zombienet-macos -p native spawn network.toml`

Example `network.toml` file:
```
[relaychain]
chain = "rococo-local"
default_command = "/Users/bruno/Library/Caches/pop/polkadot-v1.8.0"

[[relaychain.nodes]]
name = "alice"
validator = true

[[relaychain.nodes]]
name = "bob"
validator = true

[[parachains]]
id = 9090
default_command = "pop-node"

[[parachains.collators]]
name = "pop"
command = "/Users/bruno/src/pop-node/target/debug/pop-node"
args = ["-lruntime::contracts=debug"]
```

### Describe the results you received

```
(node:88613) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `zombienet-macos --trace-warnings ...` to show where the warning was created)

Error 	 fetching metrics from: http://127.0.0.1:56776/metrics

Error 	 fetching metrics from: http://127.0.0.1:56780/metrics

Error 	 fetching metrics from: http://127.0.0.1:56784/metrics

Error 	 fetching metrics from: http://127.0.0.1:56776/metrics
```

### Describe the results you expected

Previously the network would boot up fine.

### Zombienet version

v1.3.100

### Provider

Native

### Provider version

```yaml
## For binaries
polkadot 1.10.0
```

### Upstream Latest Release

Yes

### Additional environment details

Additional environment details

### Additional information

Full output: https://gist.github.com/brunopgalvao/6ecc0af03960105d07419caf50771be1#file-zombienet_error

**Comment by pepoviola** [comment] 2024-05-01 10:35
Hi @brunopgalvao, thanks for open this and your feedback! Can you check if the process are alive checking the logs? Those should be in the tmp folder (in your logs /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombiefab3e0b5d0f9f506fc27a7a02dc7715e_-88613-zQW9tYRx7D9G ).
Thanks!!

**Comment by brunopgalvao** [comment] 2024-05-01 11:25
Heyy @pepoviola 

I ran this command:
```
rm -rf /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-*
```
Then re-ran:
```
./zombienet-macos -p native spawn network.toml
```
Still same issue. Anything else I need to delete?

**Comment by JayPavlina** [comment] 2024-05-01 18:14
I had the same error, and I checked my node log and it crashed.

**Comment by pepoviola** [comment] 2024-05-01 23:12
Hi @JayPavlina, thanks for the update! Can you post the crash log to review if is caused by some misconfiguration of zombienet.

Thanks!

**Comment by brunopgalvao** [comment] 2024-05-02 04:01
### Logs
alice.log
```
bruno@Brunos-MacBook-Pro zombienet % cat /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/alice.log 
2024-05-02 12:57:46 Parity Polkadot    
2024-05-02 12:57:46 ✌️  version 1.8.0-ec7817e5adc    
2024-05-02 12:57:46 ❤️  by Parity Technologies <admin@parity.io>, 2017-2024    
2024-05-02 12:57:46 📋 Chain specification: Rococo Local Testnet    
2024-05-02 12:57:46 🏷  Node name: alice    
2024-05-02 12:57:46 👤 Role: AUTHORITY    
2024-05-02 12:57:46 💾 Database: RocksDb at /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/alice/data/chains/rococo_local_testnet/db/full    
2024-05-02 12:57:49 🔨 Initializing Genesis block/state (state: 0x6664…55cc, header-hash: 0x3743…46e5)    
2024-05-02 12:57:49 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2024-05-02 12:57:50 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2024-05-02 12:57:50 Essential task `basic-block-import-worker` failed. Shutting down service.    
Error: 
   0: Version of worker binary (1.11.0) is different from node version (1.8.0), worker_path: /Users/bruno/Library/Caches/pop/polkadot-prepare-worker. If you ran with `cargo run`, please run `cargo build` first, otherwise try to `cargo clean`. TESTING ONLY: this check can be disabled with --disable-worker-version-check

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: backtrace::capture::Backtrace::new::h7e02400e839d9b77
      at <unknown source file>:<unknown line>
   2: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::h8ef2197d2ef251e4
      at <unknown source file>:<unknown line>
   3: eyre::capture_handler::he84fc7d550666902
      at <unknown source file>:<unknown line>
   4: eyre::error::<impl eyre::Report>::from_std::h83528952fbb9a1c6
      at <unknown source file>:<unknown line>
   5: polkadot::main::h4d4f1a0a79913e03
      at <unknown source file>:<unknown line>
   6: std::sys_common::backtrace::__rust_begin_short_backtrace::h83643d2cb0a0f582
      at <unknown source file>:<unknown line>
   7: std::rt::lang_start::{{closure}}::hecb26ce148917e8e
      at <unknown source file>:<unknown line>
   8: std::rt::lang_start_internal::h5b246d44f1526226
      at <unknown source file>:<unknown line>
   9: std::rt::lang_start::h3b3473ef4813bb91
      at <unknown source file>:<unknown line>
  10: _main<unknown>
      at <unknown source file>:<unknown line>
```

bob.log
```
bruno@Brunos-MacBook-Pro zombienet % cat /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/bob.log
2024-05-02 12:57:53 Parity Polkadot    
2024-05-02 12:57:53 ✌️  version 1.8.0-ec7817e5adc    
2024-05-02 12:57:53 ❤️  by Parity Technologies <admin@parity.io>, 2017-2024    
2024-05-02 12:57:53 📋 Chain specification: Rococo Local Testnet    
2024-05-02 12:57:53 🏷  Node name: bob    
2024-05-02 12:57:53 👤 Role: AUTHORITY    
2024-05-02 12:57:53 💾 Database: RocksDb at /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/bob/data/chains/rococo_local_testnet/db/full    
2024-05-02 12:57:55 🔨 Initializing Genesis block/state (state: 0x6664…55cc, header-hash: 0x3743…46e5)    
2024-05-02 12:57:55 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2024-05-02 12:57:56 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2024-05-02 12:57:56 Essential task `basic-block-import-worker` failed. Shutting down service.    
Error: 
   0: Version of worker binary (1.11.0) is different from node version (1.8.0), worker_path: /Users/bruno/Library/Caches/pop/polkadot-prepare-worker. If you ran with `cargo run`, please run `cargo build` first, otherwise try to `cargo clean`. TESTING ONLY: this check can be disabled with --disable-worker-version-check

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: backtrace::capture::Backtrace::new::h7e02400e839d9b77
      at <unknown source file>:<unknown line>
   2: color_eyre::config::EyreHook::into_eyre_hook::{{closure}}::h8ef2197d2ef251e4
      at <unknown source file>:<unknown line>
   3: eyre::capture_handler::he84fc7d550666902
      at <unknown source file>:<unknown line>
   4: eyre::error::<impl eyre::Report>::from_std::h83528952fbb9a1c6
      at <unknown source file>:<unknown line>
   5: polkadot::main::h4d4f1a0a79913e03
      at <unknown source file>:<unknown line>
   6: std::sys_common::backtrace::__rust_begin_short_backtrace::h83643d2cb0a0f582
      at <unknown source file>:<unknown line>
   7: std::rt::lang_start::{{closure}}::hecb26ce148917e8e
      at <unknown source file>:<unknown line>
   8: std::rt::lang_start_internal::h5b246d44f1526226
      at <unknown source file>:<unknown line>
   9: std::rt::lang_start::h3b3473ef4813bb91
      at <unknown source file>:<unknown line>
  10: _main<unknown>
      at <unknown source file>:<unknown line>
```


pop.log
```
bruno@Brunos-MacBook-Pro zombienet % cat /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/pop.log
2024-05-02 12:57:57.589  INFO main sc_cli::runner: Pop Collator    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: ✌️  version 0.1.0-alpha-c8b0e73deb4    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: ❤️  by R0GUE <go@r0gue.io>, 2023-2024    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 📋 Chain specification: Pop Network Development    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 🏷  Node name: pop    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 👤 Role: AUTHORITY    
2024-05-02 12:57:57.592  INFO main sc_cli::runner: 💾 Database: RocksDb at /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/pop/data/chains/pop-devnet/db/full    
CLI parameter `--execution` has no effect anymore and will be removed in the future!
2024-05-02 12:58:00.793  INFO main pop_node::command: Parachain Account: 5Ec4AhPDLB6s1Eh1rgFupd7KA9EAfDpamAdh7YDAQT2mc9bH    
2024-05-02 12:58:00.794  INFO main pop_node::command: Is collating: yes    
2024-05-02 12:58:16.623  INFO main sc_service::client::client: [Parachain] 🔨 Initializing Genesis block/state (state: 0xb0a4…2024, header-hash: 0xdf7f…515c)    
2024-05-02 12:58:49.023  INFO main sc_service::client::client: [Relaychain] 🔨 Initializing Genesis block/state (state: 0x6664…55cc, header-hash: 0x3743…46e5)    
2024-05-02 12:58:49.061  INFO main grandpa: [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
bruno@Brunos-MacBook-Pro zombienet % cat /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/pop.log
2024-05-02 12:57:57.589  INFO main sc_cli::runner: Pop Collator    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: ✌️  version 0.1.0-alpha-c8b0e73deb4    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: ❤️  by R0GUE <go@r0gue.io>, 2023-2024    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 📋 Chain specification: Pop Network Development    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 🏷  Node name: pop    
2024-05-02 12:57:57.591  INFO main sc_cli::runner: 👤 Role: AUTHORITY    
2024-05-02 12:57:57.592  INFO main sc_cli::runner: 💾 Database: RocksDb at /var/folders/vl/txnq6gdj22s9rn296z0md27w0000gn/T/zombie-571e554b5512c014aae4811afa491c1e_-81615-9sg3g6IpAGAb/pop/data/chains/pop-devnet/db/full    
CLI parameter `--execution` has no effect anymore and will be removed in the future!
2024-05-02 12:58:00.793  INFO main pop_node::command: Parachain Account: 5Ec4AhPDLB6s1Eh1rgFupd7KA9EAfDpamAdh7YDAQT2mc9bH    
2024-05-02 12:58:00.794  INFO main pop_node::command: Is collating: yes    
2024-05-02 12:58:16.623  INFO main sc_service::client::client: [Parachain] 🔨 Initializing Genesis block/state (state: 0xb0a4…2024, header-hash: 0xdf7f…515c)    
2024-05-02 12:58:49.023  INFO main sc_service::client::client: [Relaychain] 🔨 Initializing Genesis block/state (state: 0x6664…55cc, header-hash: 0x3743…46e5)    
2024-05-02 12:58:49.061  INFO main grandpa: [Relaychain] 👴 Loading GRANDPA authority set from genesis on what appears to be first startup.    
2024-05-02 12:59:06.101  INFO main babe: [Relaychain] 👶 Creating empty BABE epoch changes on what appears to be first startup.    
2024-05-02 12:59:06.182  INFO main sub-libp2p: [Relaychain] 🏷  Local node identity is: 12D3KooWMu3Zpuh1Y1Z6f1WT6upFrFJNpEJ2wz6DYJDfSpDvBvYW    
2024-05-02 12:59:06.236  INFO main sc_sysinfo: [Relaychain] 💻 Operating system: macos    
2024-05-02 12:59:06.236  INFO main sc_sysinfo: [Relaychain] 💻 CPU architecture: aarch64    
2024-05-02 12:59:06.236  INFO main sc_service::builder: [Relaychain] 📦 Highest known block at #0    
2024-05-02 12:59:06.239  INFO tokio-runtime-worker substrate_prometheus_endpoint: [Relaychain] 〽️ Prometheus exporter started at 127.0.0.1:9616    
2024-05-02 12:59:06.669  INFO                 main sc_rpc_server: [Relaychain] Running JSON-RPC server: addr=127.0.0.1:54749, allowed origins=["http://localhost:*", "http://127.0.0.1:*", "https://localhost:*", "https://127.0.0.1:*", "https://polkadot.js.org"]    
2024-05-02 12:59:06.671  INFO                 main sc_sysinfo: [Relaychain] 🏁 CPU score: 38.85 MiBs    
2024-05-02 12:59:06.671  INFO                 main sc_sysinfo: [Relaychain] 🏁 Memory score: 38.85 GiBs    
2024-05-02 12:59:06.671  INFO                 main sc_sysinfo: [Relaychain] 🏁 Disk score (seq. writes): 1.95 GiBs    
2024-05-02 12:59:06.671  INFO                 main sc_sysinfo: [Relaychain] 🏁 Disk score (rand. writes): 335.67 MiBs    
2024-05-02 12:59:06.697  WARN                 main sc_service::config: [Parachain] Using default protocol ID "sup" because none is configured in the chain specs    
2024-05-02 12:59:06.709  INFO                 main sub-libp2p: [Parachain] 🏷  Local node identity is: 12D3KooWHu4SWm16kvy24RKeET7HZ1ZwoQr2ko9GUB8Lm7waNsdf    
2024-05-02 12:59:06.719  INFO                 main sc_sysinfo: [Parachain] 💻 Operating system: macos    
2024-05-02 12:59:06.719  INFO                 main sc_sysinfo: [Parachain] 💻 CPU architecture: aarch64    
2024-05-02 12:59:06.719  INFO                 main sc_service::builder: [Parachain] 📦 Highest known block at #0    
2024-05-02 12:59:06.720  INFO tokio-runtime-worker substrate_prometheus_endpoint: [Parachain] 〽️ Prometheus exporter started at 0.0.0.0:54699    
2024-05-02 12:59:06.722  INFO                 main sc_rpc_server: [Parachain] Running JSON-RPC server: addr=0.0.0.0:54697, allowed origins=["*"]    
2024-05-02 12:59:06.723  INFO                 main sc_sysinfo: [Parachain] 🏁 CPU score: 38.85 MiBs    
2024-05-02 12:59:06.723  INFO                 main sc_sysinfo: [Parachain] 🏁 Memory score: 38.85 GiBs    
2024-05-02 12:59:06.723  INFO                 main sc_sysinfo: [Parachain] 🏁 Disk score (seq. writes): 1.95 GiBs    
2024-05-02 12:59:06.723  INFO                 main sc_sysinfo: [Parachain] 🏁 Disk score (rand. writes): 335.67 MiBs    
2024-05-02 12:59:06.723  WARN                 main pop_node::service: [Parachain] ⚠️  The hardware does not meet the minimal requirements for role 'Authority'.    
2024-05-02 12:59:07.706  INFO tokio-runtime-worker libp2p_mdns::behaviour: [Relaychain] discovered: 12D3KooWHu4SWm16kvy24RKeET7HZ1ZwoQr2ko9GUB8Lm7waNsdf /ip4/192.168.0.48/tcp/54696/ws    
2024-05-02 12:59:07.707  INFO tokio-runtime-worker libp2p_mdns::behaviour: [Parachain] discovered: 12D3KooWMu3Zpuh1Y1Z6f1WT6upFrFJNpEJ2wz6DYJDfSpDvBvYW /ip4/192.168.0.48/tcp/54748/ws    
2024-05-02 12:59:11.676  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (0 peers), best: #0 (0x3743…46e5), finalized #0 (0x3743…46e5), ⬇ 0.2kiB/s ⬆ 0.5kiB/s    
2024-05-02 12:59:11.854  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #0 (0xdf7f…515c), finalized #0 (0xdf7f…515c), ⬇ 0.5kiB/s ⬆ 0.2kiB/s 
```

**Comment by brunopgalvao** [comment] 2024-05-02 04:49
So... I updated the binary to `v1.11.0` and the network spins up - so I am good.

To note, I still get the message: `Error fetching metrics from: http://127.0.0.1:56846/metrics`

**Comment by ntn-x2** [comment] 2024-05-02 05:54
+1 for me. I had already opened an issue a while ago on a previous version of the Zombienet CLI: https://github.com/paritytech/zombienet/issues/1578. I went back to it now, using zombienet `1.3.100` and the issue persists. I also found out about https://github.com/paritytech/zombienet/issues/1730#issuecomment-1962408526 as a workaround, which SEEMS to work, at least the only one time I spun up the network with the new flag set.

**Comment by ntn-x2** [comment] 2024-05-02 06:00
Nevermind, one of the containers dies after few dozens of seconds, and does not recover. It's probably a different error tho.

**Comment by pepoviola** [comment] 2024-05-02 07:29
Yes, you can set `node_verifier = "None"` to bypass the check using prometheus. We don't try to recover pods since if crash at the begging of the spawning phase most of the time if because a configuration or non-recoverable error.

Thx!

**Comment by pepoviola** [comment] 2024-05-02 07:30
> So... I updated the binary to `v1.11.0` and the network spins up - so I am good.
> 
> To note, I still get the message: `Error fetching metrics from: http://127.0.0.1:56846/metrics`

Thanks for the update @brunopgalvao, did you get a couple of these and then the network spawn correctly right?

Thx!

**Comment by pepoviola** [comment] 2024-05-06 14:25
Thanks @brunopgalvao, the output is ok (fail a couple of times before prometheus start responding). We could maybe mute the output at some point.
Closing here.
Thx!

**Closed by pepoviola** 2024-05-06 14:25 UTC
Labels: question
